server:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
api:
  version: 0.0.1


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/tickets/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventories/**